### ISSUE TITLE
Add Fast Palm AI ChatBot 💬 in list

### ISSUE THREAD

**Issue by imabutahersiddik** [awesome-gptX/awesome-gpt#163]
**Website URL**

```
https://fast-palm-ai-chatbot.vercel.app
```

**Website Type**

- [x] Chatbot Ai site
- [ ] Other

**Website Description and Usage**

> Please provide a clear description to help others understand how to use it.

- [x] 😄 Free to use (open and ready to use with no restrictions, uses your device threads)
- [ ] 🔑 Free to use, but requires login or password
- [ ] 🤑 Paid service
- [ ] 🎁 Paid service with a trial period

**Website Icon - Path (optional)**
> Square-shaped icon

```
For example: https://fast-palm-ai-chatbot.vercel.app/img/robot.png
```

**Requires International Access (optional)**

- [x] No
- [ ] Yes

**Comment by edison1105** [comment]
PR welcome.
